<?php

namespace zetsoft\inserts\eyuf;

use zetsoft\system\actives\ZInsert;
use zetsoft\system\Az;
use zetsoft\system\kernels\ZMigration;
use zetsoft\models\core\CoreInput;

class CoreInputInsert extends ZInsert
{

    public function run()
    {

        $this->model = new CoreInput();

        $this->model->id = 5;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->jsonb_1 = "";
        $this->model->jsonb_2 = "";
        $this->model->jsonb_3 = "";
        $this->model->jsonb_4 = "";
        $this->model->jsonb_5 = "";
        $this->model->jsonb_6 = "";
        $this->model->jsonb_7 = "";
        $this->model->jsonb_8 = "";
        $this->model->jsonb_9 = "";
        $this->model->jsonb_10 = "";
        $this->model->int_1 = null;
        $this->model->int_2 = null;
        $this->model->int_3 = null;
        $this->model->int_4 = null;
        $this->model->int_5 = null;
        $this->model->int_6 = null;
        $this->model->int_7 = null;
        $this->model->int_8 = null;
        $this->model->int_9 = null;
        $this->model->int_10 = null;
        $this->model->string_1 = '';
        $this->model->string_2 = '';
        $this->model->string_3 = '';
        $this->model->string_4 = '';
        $this->model->string_5 = '';
        $this->model->string_6 = '';
        $this->model->string_7 = '';
        $this->model->string_8 = '';
        $this->model->string_9 = '';
        $this->model->string_10 = '';
        $this->model->bool_1 = null;
        $this->model->bool_2 = null;
        $this->model->bool_3 = null;
        $this->model->bool_4 = null;
        $this->model->bool_5 = null;
        $this->model->text_1 = '';
        $this->model->text_2 = '';
        $this->model->text_3 = '';
        $this->model->text_4 = '';
        $this->model->text_5 = '';
        $this->model->date_1 = null;
        $this->model->date_2 = null;
        $this->model->date_3 = null;
        $this->model->date_4 = null;
        $this->model->date_5 = null;
        $this->model->time_1 = null;
        $this->model->time_2 = null;
        $this->model->time_3 = null;
        $this->model->time_4 = null;
        $this->model->time_5 = null;
        $this->save();


        $this->model = new CoreInput();

        $this->model->id = 4;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->jsonb_1 = "";
        $this->model->jsonb_2 = "";
        $this->model->jsonb_3 = "";
        $this->model->jsonb_4 = "";
        $this->model->jsonb_5 = "";
        $this->model->jsonb_6 = "";
        $this->model->jsonb_7 = "";
        $this->model->jsonb_8 = "";
        $this->model->jsonb_9 = "";
        $this->model->jsonb_10 = "";
        $this->model->int_1 = null;
        $this->model->int_2 = null;
        $this->model->int_3 = null;
        $this->model->int_4 = null;
        $this->model->int_5 = null;
        $this->model->int_6 = null;
        $this->model->int_7 = null;
        $this->model->int_8 = null;
        $this->model->int_9 = null;
        $this->model->int_10 = null;
        $this->model->string_1 = '';
        $this->model->string_2 = '';
        $this->model->string_3 = '';
        $this->model->string_4 = '';
        $this->model->string_5 = '';
        $this->model->string_6 = '';
        $this->model->string_7 = '';
        $this->model->string_8 = '';
        $this->model->string_9 = '';
        $this->model->string_10 = '';
        $this->model->bool_1 = null;
        $this->model->bool_2 = null;
        $this->model->bool_3 = null;
        $this->model->bool_4 = null;
        $this->model->bool_5 = null;
        $this->model->text_1 = '';
        $this->model->text_2 = '';
        $this->model->text_3 = '';
        $this->model->text_4 = '';
        $this->model->text_5 = '';
        $this->model->date_1 = null;
        $this->model->date_2 = null;
        $this->model->date_3 = null;
        $this->model->date_4 = null;
        $this->model->date_5 = null;
        $this->model->time_1 = null;
        $this->model->time_2 = null;
        $this->model->time_3 = null;
        $this->model->time_4 = null;
        $this->model->time_5 = null;
        $this->save();


        $this->model = new CoreInput();

        $this->model->id = 3;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->jsonb_1 = "";
        $this->model->jsonb_2 = "";
        $this->model->jsonb_3 = "";
        $this->model->jsonb_4 = "";
        $this->model->jsonb_5 = "";
        $this->model->jsonb_6 = "";
        $this->model->jsonb_7 = "";
        $this->model->jsonb_8 = "";
        $this->model->jsonb_9 = "";
        $this->model->jsonb_10 = "";
        $this->model->int_1 = null;
        $this->model->int_2 = null;
        $this->model->int_3 = null;
        $this->model->int_4 = null;
        $this->model->int_5 = null;
        $this->model->int_6 = null;
        $this->model->int_7 = null;
        $this->model->int_8 = null;
        $this->model->int_9 = null;
        $this->model->int_10 = null;
        $this->model->string_1 = '';
        $this->model->string_2 = '';
        $this->model->string_3 = '';
        $this->model->string_4 = '';
        $this->model->string_5 = '';
        $this->model->string_6 = '';
        $this->model->string_7 = '';
        $this->model->string_8 = '';
        $this->model->string_9 = '';
        $this->model->string_10 = '';
        $this->model->bool_1 = null;
        $this->model->bool_2 = null;
        $this->model->bool_3 = null;
        $this->model->bool_4 = null;
        $this->model->bool_5 = null;
        $this->model->text_1 = '';
        $this->model->text_2 = '';
        $this->model->text_3 = '';
        $this->model->text_4 = '';
        $this->model->text_5 = '';
        $this->model->date_1 = null;
        $this->model->date_2 = null;
        $this->model->date_3 = null;
        $this->model->date_4 = null;
        $this->model->date_5 = null;
        $this->model->time_1 = null;
        $this->model->time_2 = null;
        $this->model->time_3 = null;
        $this->model->time_4 = null;
        $this->model->time_5 = null;
        $this->save();


        $this->model = new CoreInput();

        $this->model->id = 7;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->jsonb_1 = "";
        $this->model->jsonb_2 = "";
        $this->model->jsonb_3 = "";
        $this->model->jsonb_4 = "";
        $this->model->jsonb_5 = "";
        $this->model->jsonb_6 = "";
        $this->model->jsonb_7 = "";
        $this->model->jsonb_8 = "";
        $this->model->jsonb_9 = "";
        $this->model->jsonb_10 = "";
        $this->model->int_1 = null;
        $this->model->int_2 = null;
        $this->model->int_3 = null;
        $this->model->int_4 = null;
        $this->model->int_5 = null;
        $this->model->int_6 = null;
        $this->model->int_7 = null;
        $this->model->int_8 = null;
        $this->model->int_9 = null;
        $this->model->int_10 = null;
        $this->model->string_1 = '1';
        $this->model->string_2 = '';
        $this->model->string_3 = '';
        $this->model->string_4 = '';
        $this->model->string_5 = '';
        $this->model->string_6 = '';
        $this->model->string_7 = '';
        $this->model->string_8 = '';
        $this->model->string_9 = '';
        $this->model->string_10 = '';
        $this->model->bool_1 = null;
        $this->model->bool_2 = null;
        $this->model->bool_3 = null;
        $this->model->bool_4 = null;
        $this->model->bool_5 = null;
        $this->model->text_1 = '';
        $this->model->text_2 = '';
        $this->model->text_3 = '';
        $this->model->text_4 = '';
        $this->model->text_5 = '';
        $this->model->date_1 = null;
        $this->model->date_2 = null;
        $this->model->date_3 = null;
        $this->model->date_4 = null;
        $this->model->date_5 = null;
        $this->model->time_1 = null;
        $this->model->time_2 = null;
        $this->model->time_3 = null;
        $this->model->time_4 = null;
        $this->model->time_5 = null;
        $this->save();


        $this->model = new CoreInput();

        $this->model->id = 8;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->jsonb_1 = "";
        $this->model->jsonb_2 = "";
        $this->model->jsonb_3 = "";
        $this->model->jsonb_4 = "";
        $this->model->jsonb_5 = "";
        $this->model->jsonb_6 = "";
        $this->model->jsonb_7 = "";
        $this->model->jsonb_8 = "";
        $this->model->jsonb_9 = "";
        $this->model->jsonb_10 = "";
        $this->model->int_1 = null;
        $this->model->int_2 = null;
        $this->model->int_3 = null;
        $this->model->int_4 = null;
        $this->model->int_5 = null;
        $this->model->int_6 = null;
        $this->model->int_7 = null;
        $this->model->int_8 = null;
        $this->model->int_9 = null;
        $this->model->int_10 = null;
        $this->model->string_1 = '';
        $this->model->string_2 = '';
        $this->model->string_3 = '';
        $this->model->string_4 = '';
        $this->model->string_5 = '';
        $this->model->string_6 = '';
        $this->model->string_7 = '';
        $this->model->string_8 = '';
        $this->model->string_9 = '';
        $this->model->string_10 = '';
        $this->model->bool_1 = null;
        $this->model->bool_2 = null;
        $this->model->bool_3 = null;
        $this->model->bool_4 = null;
        $this->model->bool_5 = null;
        $this->model->text_1 = '';
        $this->model->text_2 = '';
        $this->model->text_3 = '';
        $this->model->text_4 = '';
        $this->model->text_5 = '';
        $this->model->date_1 = null;
        $this->model->date_2 = null;
        $this->model->date_3 = null;
        $this->model->date_4 = null;
        $this->model->date_5 = null;
        $this->model->time_1 = null;
        $this->model->time_2 = null;
        $this->model->time_3 = null;
        $this->model->time_4 = null;
        $this->model->time_5 = null;
        $this->save();


        $this->model = new CoreInput();

        $this->model->id = 9;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->jsonb_1 = "";
        $this->model->jsonb_2 = "";
        $this->model->jsonb_3 = "";
        $this->model->jsonb_4 = "";
        $this->model->jsonb_5 = "";
        $this->model->jsonb_6 = "";
        $this->model->jsonb_7 = "";
        $this->model->jsonb_8 = "";
        $this->model->jsonb_9 = "";
        $this->model->jsonb_10 = "";
        $this->model->int_1 = null;
        $this->model->int_2 = null;
        $this->model->int_3 = null;
        $this->model->int_4 = null;
        $this->model->int_5 = null;
        $this->model->int_6 = null;
        $this->model->int_7 = null;
        $this->model->int_8 = null;
        $this->model->int_9 = null;
        $this->model->int_10 = null;
        $this->model->string_1 = '';
        $this->model->string_2 = '';
        $this->model->string_3 = '';
        $this->model->string_4 = '';
        $this->model->string_5 = '';
        $this->model->string_6 = '';
        $this->model->string_7 = '';
        $this->model->string_8 = '';
        $this->model->string_9 = '';
        $this->model->string_10 = '';
        $this->model->bool_1 = null;
        $this->model->bool_2 = null;
        $this->model->bool_3 = null;
        $this->model->bool_4 = null;
        $this->model->bool_5 = null;
        $this->model->text_1 = '';
        $this->model->text_2 = '';
        $this->model->text_3 = '';
        $this->model->text_4 = '';
        $this->model->text_5 = '';
        $this->model->date_1 = null;
        $this->model->date_2 = null;
        $this->model->date_3 = null;
        $this->model->date_4 = null;
        $this->model->date_5 = null;
        $this->model->time_1 = null;
        $this->model->time_2 = null;
        $this->model->time_3 = null;
        $this->model->time_4 = null;
        $this->model->time_5 = null;
        $this->save();


    }

}
