<?php

namespace zetsoft\inserts\eyuf;

use zetsoft\system\actives\ZInsert;
use zetsoft\system\Az;
use zetsoft\system\kernels\ZMigration;
use zetsoft\models\dyna\DynaChessItem;

class DynaChessItemInsert extends ZInsert
{

    public function run()
    {

        $this->model = new DynaChessItem();

        $this->model->id = 25;
        $this->model->sort = 25;
        $this->model->name = 'unervisal_report';
        $this->model->title = 'UNIVERSIAL REPORT TEST';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 1;
        $this->model->service = "";
        $this->model->type = 'hasMulti';
        $this->model->formula = '';
        $this->model->models = 'WareEnterItem';
        $this->model->relate_attr = 'shop_catalog_ware_id';
        $this->model->attrib = 'amount';
        $this->model->process = 'sum';
        $this->model->filter = 1;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 21;
        $this->model->sort = 21;
        $this->model->name = 'attr12';
        $this->model->title = 'Приход от ВДС';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 2;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 17;
        $this->model->sort = 17;
        $this->model->name = 'attr7';
        $this->model->title = 'Расход';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 2;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = 1;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 43;
        $this->model->sort = 43;
        $this->model->name = 'Новая запись 43';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = null;
        $this->model->dyna_chess_id = 13;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 53;
        $this->model->sort = 53;
        $this->model->name = 'attr1';
        $this->model->title = 'заказы, полученные курьером';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 49;
        $this->model->service = "";
        $this->model->type = 'hasOne';
        $this->model->formula = '';
        $this->model->models = 'ShopShipment';
        $this->model->relate_attr = 'shop_shipment_id';
        $this->model->attrib = '';
        $this->model->process = 'sum';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 15;
        $this->model->sort = 15;
        $this->model->name = 'amount_before';
        $this->model->title = 'Началный остаток';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 2;
        $this->model->service = "";
        $this->model->type = 'native';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = 'id';
        $this->model->process = '';
        $this->model->filter = 1;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 58;
        $this->model->sort = 58;
        $this->model->name = 'a';
        $this->model->title = 'Процент';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 53;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 18;
        $this->model->sort = 18;
        $this->model->name = 'amount_after';
        $this->model->title = 'Конечный остаток';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 2;
        $this->model->service = "";
        $this->model->type = 'hasOne';
        $this->model->formula = '';
        $this->model->models = 'User';
        $this->model->relate_attr = 'modified_by';
        $this->model->attrib = 'amount_history';
        $this->model->process = '';
        $this->model->filter = 1;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 56;
        $this->model->sort = 56;
        $this->model->name = 'sda';
        $this->model->title = 'Всего';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 53;
        $this->model->service = "";
        $this->model->type = 'native';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = 'total';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 52;
        $this->model->sort = 52;
        $this->model->name = 'create_at';
        $this->model->title = 'for testing purpose';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 51;
        $this->model->service = "";
        $this->model->type = 'hasMany';
        $this->model->formula = '';
        $this->model->models = 'WareReturn';
        $this->model->relate_attr = 'ware_id';
        $this->model->attrib = 'total_price';
        $this->model->process = 'sum';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 49;
        $this->model->sort = 49;
        $this->model->name = 'something_to_do';
        $this->model->title = 'for testing purpose';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 1;
        $this->model->service = "";
        $this->model->type = 'hasMany';
        $this->model->formula = '';
        $this->model->models = 'WareExitItem';
        $this->model->relate_attr = 'shop_catalog_ware_id';
        $this->model->attrib = 'shop_element_id';
        $this->model->process = 'count';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 19;
        $this->model->sort = 19;
        $this->model->name = 'attr10';
        $this->model->title = 'Приход от обмен';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 2;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 16;
        $this->model->sort = 16;
        $this->model->name = 'attr6';
        $this->model->title = 'Приход';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = null;
        $this->model->dyna_chess_id = 2;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 20;
        $this->model->sort = 20;
        $this->model->name = 'attr11';
        $this->model->title = 'Отменено';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 2;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 55;
        $this->model->sort = 55;
        $this->model->name = 'asad2';
        $this->model->title = 'Курьер';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 53;
        $this->model->service = "";
        $this->model->type = 'hasOne';
        $this->model->formula = '';
        $this->model->models = 'ShopCourier';
        $this->model->relate_attr = 'shop_courier_id';
        $this->model->attrib = 'name';
        $this->model->process = '';
        $this->model->filter = 1;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 14;
        $this->model->sort = 14;
        $this->model->name = 'year';
        $this->model->title = 'Годен до';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 2;
        $this->model->service = "";
        $this->model->type = 'native';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = 'best_before';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 50;
        $this->model->sort = 50;
        $this->model->name = 'amount_wares';
        $this->model->title = 'somehting';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 51;
        $this->model->service = "";
        $this->model->type = 'hasOne';
        $this->model->formula = '';
        $this->model->models = 'PlaceAdress';
        $this->model->relate_attr = 'place_adress_id';
        $this->model->attrib = 'created_at';
        $this->model->process = 'sum';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 44;
        $this->model->sort = 44;
        $this->model->name = 'Новая запись 44';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = null;
        $this->model->dyna_chess_id = 13;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 60;
        $this->model->sort = 60;
        $this->model->name = 'asdas';
        $this->model->title = 'Процент переносов';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = null;
        $this->model->dyna_chess_id = 53;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 59;
        $this->model->sort = 59;
        $this->model->name = 'as';
        $this->model->title = 'Перенос';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 53;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 57;
        $this->model->sort = 57;
        $this->model->name = 'dsfsd';
        $this->model->title = 'Выкуп';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->dyna_chess_id = 53;
        $this->model->service = "";
        $this->model->type = 'native';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = 'completed';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 61;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = null;
        $this->model->dyna_chess_id = 4;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 62;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = null;
        $this->model->dyna_chess_id = 4;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 63;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = null;
        $this->model->dyna_chess_id = 4;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 64;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = null;
        $this->model->dyna_chess_id = 4;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


        $this->model = new DynaChessItem();

        $this->model->id = 66;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = null;
        $this->model->dyna_chess_id = null;
        $this->model->service = "";
        $this->model->type = '';
        $this->model->formula = '';
        $this->model->models = '';
        $this->model->relate_attr = '';
        $this->model->attrib = '';
        $this->model->process = '';
        $this->model->filter = null;
        $this->model->filter_widget = '';
        $this->model->column_data = '';
        $this->model->group = null;
        $this->model->grouped_row = null;
        $this->model->sorting = null;
        $this->model->item_class = '';
        $this->model->item_attr = '';
        $this->model->summary = null;
        $this->model->summary_type = 'f_sum';
        $this->model->hide_null = null;
        $this->model->deleted_at = null;
        $this->model->deleted_by = null;
        $this->model->deleted_text = '';
        $this->model->created_at = '';
        $this->model->modified_at = '';
        $this->model->created_by = null;
        $this->model->modified_by = null;
        $this->save();


    }

}
