<?php

namespace zetsoft\inserts\eyuf;

use zetsoft\system\actives\ZInsert;
use zetsoft\system\Az;
use zetsoft\system\kernels\ZMigration;
use zetsoft\models\user\User;

class UserInsert extends ZInsert
{

    public function run()
    {

        $this->model = new User();

        $this->model->id = 91;
        $this->model->sort = null;
        $this->model->name = 'Ivan Ivanov Ivanovich |  | nshaxrizod@list.ru';
        $this->model->guid = '';
        $this->model->title = 'Ivan Ivanov Ivanovich';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'nshaxrizod@list.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-11-03 15:27:55';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = '2kYk3GXhZaeAAW7ShSmfevs3efgNsmeQHpsu3HSjQ8WgBrPXsJ7Kk6a8JayGZKDg';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 112;
        $this->model->sort = null;
        $this->model->name = ' |  | dardasamli@nedoz.com';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'dardasamli@nedoz.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'uskBcBRaG322d4VFKJyU2cUDNprjNr462DRKZ4jNstJYpuE9jupNppWWhjeQPWzu';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 135;
        $this->model->sort = null;
        $this->model->name = ' |  | fe';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
        $this->model->role = '';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'fe';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = null;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 137;
        $this->model->sort = null;
        $this->model->name = ' |  | jakh.kudratov@gmail.com';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'jakh.kudratov@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-11-02 10:36:25';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'bDqtb8JK867HexdgFQttXzAZCZ3NvwyWMPSs6KqF64FQDwrtQK7djCVHXYgHEvN5';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = 267;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 87;
        $this->model->sort = null;
        $this->model->name = 'user9196 |  | zetsoftenterprise@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user9196';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = 'f86b73533df57c0f255399208a0f8d2a590fb123bc4ffa21f3e650f3f66ed1f0';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'zetsoftenterprise@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '45fd3921b52a9fba13c1fed8f87498403275e683dd82166778f0b983ab157bab';
        $this->model->verified_email = null;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'mcGufq78wfbyfGfyEbvdWYG7T2m8xNN9t6Hb3m3zDwfVEw93fbe6dRkfkjtUztnM';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 86;
        $this->model->sort = null;
        $this->model->name = 'user2507 |  | azimjon.toirov@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user2507';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'accounter';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'azimjon.toirov@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-10-16 16:57:01';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '62ffca3230ee975f568a4ed284b9a6115c6c279530ea18c2fb1664f071713dc4';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'ubefxr5YYhKXRcCCm47cRJ7QMrGJcUTW9MbvyV4h2KKu2r5HfNAGEAka2A3TEHMk';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 88;
        $this->model->sort = null;
        $this->model->name = 'user9100 |  | alimov.behzod@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user9100';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'alimov.behzod@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'Wu3MQPu6fN5JHFy3wqCSD4AhRm5EueueVDEqBR2PeUsz8XruRBWy2xAXwAvMYEej';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 90;
        $this->model->sort = null;
        $this->model->name = 'RAVSHAN | Мужчина | ravshan@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'RAVSHAN';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'scholar';
        $this->model->gender = 'male';
        $this->model->lang = 'ru';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'ravshan@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 89;
        $this->model->sort = null;
        $this->model->name = 'user9755 |  | idontcare.student@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user9755';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'idontcare.student@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = 'a32655a67995a0871b3adba659ef6c8d7bd70924ee446dcb9957b1a417be1ac4';
        $this->model->verified_email = null;
        $this->model->verified_phone = null;
        $this->model->auth_key = '6S66YXZAMpjdf2PPK7mPF2T4fYMbbhT34uK6JBeyuvnXYSjMwPUGAGKxvYXFaJnp';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 93;
        $this->model->sort = null;
        $this->model->name = ' |  | nshaxrizod@bk.ru';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'nshaxrizod@bk.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'pcHsfdapWrSvufuvakUg3gVxe7SASaXWGsCutEpxnxbmsjwpXAzwXGBySQX8h5KN';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 95;
        $this->model->sort = null;
        $this->model->name = ' |  | sultonbekshodiyev7@gmail.com';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'sultonbekshodiyev7@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '1e3b9b69486caf8af33f59a44fd4fb137d9cae7d523d33ffddab2f1fccec31c7';
        $this->model->verified_email = null;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'WAG2WcjjdzWcTZbWshYfhmqVtKWZvNr8m7WeMtb3QNmYMG7Q5fDfvyqdaMumbAVr';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 126;
        $this->model->sort = null;
        $this->model->name = ' |  | yelmoduyde@nedoz.com';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'yelmoduyde@nedoz.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'TtwawU2kZpkgMBKrhnNaXJjWMShNRY5YdGxgRm6Z2nvYuPbmJJKTEyTtvE7x3DyK';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 122;
        $this->model->sort = null;
        $this->model->name = ' | ';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
        $this->model->role = '';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = null;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 124;
        $this->model->sort = null;
        $this->model->name = ' |  | fe';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
        $this->model->role = '';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'fe';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = null;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 138;
        $this->model->sort = null;
        $this->model->name = ' |  | fe';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
        $this->model->role = '';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'fe';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = null;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 127;
        $this->model->sort = null;
        $this->model->name = ' |  | shaxats@gmail.com';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'shaxats@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'hhKjswUrn5utHQ6X2fAdFFJzUv5CfESW8RSpEpnWE3qVcqpV8WbV3Np9HwJFmqeu';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 128;
        $this->model->sort = null;
        $this->model->name = ' | ';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
        $this->model->role = '';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 129;
        $this->model->sort = null;
        $this->model->name = ' | ';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
        $this->model->role = '';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 130;
        $this->model->sort = null;
        $this->model->name = ' | ';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
        $this->model->role = '';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 131;
        $this->model->sort = null;
        $this->model->name = ' | ';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
        $this->model->role = '';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 132;
        $this->model->sort = null;
        $this->model->name = ' | ';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
        $this->model->role = '';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 140;
        $this->model->sort = null;
        $this->model->name = 'intern | Мужчина | eyuf.intern@gmail.com | 99-999-99-99';
        $this->model->guid = '';
        $this->model->title = 'intern';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'interqua';
        $this->model->gender = 'male';
        $this->model->lang = 'ru';
        $this->model->phone = '99-999-99-99';
        $this->model->number = 9999999;
        $this->model->extpass = null;
        $this->model->email = 'eyuf.intern@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-11-02 18:55:32';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 136;
        $this->model->sort = null;
        $this->model->name = ' |  | fe';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
        $this->model->role = '';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'fe';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = null;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 85;
        $this->model->sort = null;
        $this->model->name = 'user657 |  | scholar@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user657';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'scholar@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-11-04 13:19:41';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = '5E2ZCyHfaB94vVtdKWRAH4eBvkDH3SJpqFgrgPkMEV3hjzPtsS3Ve9zPbPTpjpJY';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 143;
        $this->model->sort = null;
        $this->model->name = 'interqua | Мужчина | interqua@gmail.com | 90-987-76-76';
        $this->model->guid = '';
        $this->model->title = 'interqua';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'interqua';
        $this->model->gender = 'male';
        $this->model->lang = '';
        $this->model->phone = '90-987-76-76';
        $this->model->number = 998909878;
        $this->model->extpass = null;
        $this->model->email = 'interqua@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-11-04 14:31:08';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = 268;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 76;
        $this->model->sort = null;
        $this->model->name = 'user5409 |  | needer@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user5409';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'needer';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'needer@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-11-04 15:55:33';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'QS3snQhP58U9YjH4GKaqNEzByxWwzrNjmmuzVD2DkWvNymqzUhHVTY9PQQ9wkw8s';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 109;
        $this->model->sort = null;
        $this->model->name = ' |  | compatriot@gmail.com';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'compatriot';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'compatriot@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-11-04 16:04:25';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 139;
        $this->model->sort = null;
        $this->model->name = ' |  | fe';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
        $this->model->role = '';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'fe';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = null;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 134;
        $this->model->sort = null;
        $this->model->name = ' |  | elyurtumidifoundation@gmail.com';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'elyurtumidifoundation@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-10-26 19:57:05';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'VGmBrYPB6maBG2Hp7SHjhxFXA5YYCqQVtsFxXEv9P8hfdtCNyePHD4jhNQeM6AAd';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 133;
        $this->model->sort = null;
        $this->model->name = ' | ';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
        $this->model->role = '';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 144;
        $this->model->sort = null;
        $this->model->name = 'MathDoc | Мужчина | macdoc@gmail.com | 90-595-97-67';
        $this->model->guid = '';
        $this->model->title = 'MathDoc';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'masdoc';
        $this->model->gender = 'male';
        $this->model->lang = 'en';
        $this->model->phone = '90-595-97-67';
        $this->model->number = 905959767;
        $this->model->extpass = null;
        $this->model->email = 'macdoc@gmail.com';
        $this->model->website = 'yunsobod';
        $this->model->photo = "";
        $this->model->status = 'process';
        $this->model->lastseen = '2020-11-04 13:30:14';
        $this->model->blocked = null;
        $this->model->apiclient = 1;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = 1;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = '';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = 267;
        $this->model->place_adress_ids = [
            '1062',
            '1066',
        ];
        $this->model->currency = 'usd';
        $this->model->referal_link = 'sadasdsa';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 145;
        $this->model->sort = null;
        $this->model->name = ' |  | jamshud0427@gmail.com';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '7449c616bfd9f03444b0de9a7bf90a819b64d08d29e50cd504a1eaf2dcf2ec88';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'jamshud0427@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'PZ79bASHxh52p2KMqd7rygp9nYGrQ5BqVuky26DPMt5WsG42jQrUwWBjVpZW7KHN';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 81;
        $this->model->sort = null;
        $this->model->name = 'Jahongir |  | moderator@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'Jahongir';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'moderator';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'moderator@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-11-04 14:39:30';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'x8fe5vFQXTj7TnVdefwaGf74Ugg9SnyNxmsgzGCDj7fbAyEyNxxKRvjQZzpYfKsa';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = 267;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 141;
        $this->model->sort = null;
        $this->model->name = ' |  | jakh.kudratoff@gmail.com';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'jakh.kudratoff@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-11-04 14:54:54';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'vyENCU6PYgp6qSdMREYe3h3fwhXAKhFs443hBqqa2rZ8XrsMRYk9z7E2xqJJzrDB';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 83;
        $this->model->sort = null;
        $this->model->name = 'user7475 |  | accounter@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user7475';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'accounter';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'accounter@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-11-04 16:08:17';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'YYu3hyYx2VeYjKEskhra5mk2xWfxyyVnSHhy5H4bRnP7XA87mRsgSVeh8V5Pd2cc';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 84;
        $this->model->sort = null;
        $this->model->name = 'user2846 |  | monitor@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user2846';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'monitor';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'monitor@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-11-11 12:52:18';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'PAg9E6UQhsUYPhkfRffPx8DGCEbknG2gxbePFydXT2vFZSfv4YFvwjphyWzbAyXU';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 79;
        $this->model->sort = null;
        $this->model->name = 'user3265 |  | admin@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user3265';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'admin';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'admin@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-11-18 11:47:44';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'hKuJAR9DTcv49qQqYZ8Wx8fn54AUQYWjbyNgBQ2rAVhyzJs4kaNgZ7zR6k5XZ3nq';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = [
            'github' => '',
            'twitter' => '',
            'facebook' => '',
            'telegram' => '',
            'linked_in' => '',
            'google_plus' => '',
        ];
        $this->save();


        $this->model = new User();

        $this->model->id = 146;
        $this->model->sort = null;
        $this->model->name = ' |  | asror.z@yandex.com';
        $this->model->guid = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'scholar';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'asror.z@yandex.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'xQ9sJNpdHVS5bkEvwyhxdgMdeNMH56P2rbRUxnD88vwfJzTws8Ekfeq375hnSJmx';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


    }

}
