<?php

namespace zetsoft\inserts\mplace;

use zetsoft\system\actives\ZInsert;
use zetsoft\system\Az;
use zetsoft\system\kernels\ZMigration;
use zetsoft\models\calls\CallsCdr;

class CallsCdrInsert extends ZInsert
{

    public function run()
    {

        $this->model = new CallsCdr();

        $this->model->id = 4942;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-19 16:09:43';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/19/out-998113264-304-20201019-160943-1603105783.2.wav';
        $this->model->clid = '\\\"\\\" <304>';
        $this->model->number = '';
        $this->model->dst = '998113264';
        $this->model->src = '304';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/304-00000002';
        $this->model->dstchannel = 'SIP/etc-00000003';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/998113264,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '0';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603105783.2';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '304';
        $this->model->cnam = '304';
        $this->model->outbound_cnum = '304';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603105783.2';
        $this->model->peeraccount = '';
        $this->model->sequence = '2';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4943;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-19 16:09:51';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/19/out-998113264-304-20201019-160951-1603105791.4.wav';
        $this->model->clid = '\\\"\\\" <304>';
        $this->model->number = '';
        $this->model->dst = '998113264';
        $this->model->src = '304';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/304-00000004';
        $this->model->dstchannel = 'SIP/etc-00000005';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/998113264,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '0';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603105791.4';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '304';
        $this->model->cnam = '304';
        $this->model->outbound_cnum = '304';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603105791.4';
        $this->model->peeraccount = '';
        $this->model->sequence = '5';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4944;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-19 16:10:10';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/19/out-998113264-304-20201019-161010-1603105810.6.wav';
        $this->model->clid = '\\\"\\\" <304>';
        $this->model->number = '';
        $this->model->dst = '998113264';
        $this->model->src = '304';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/304-00000006';
        $this->model->dstchannel = 'SIP/etc-00000007';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/998113264,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '0';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603105810.6';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '304';
        $this->model->cnam = '304';
        $this->model->outbound_cnum = '304';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603105810.6';
        $this->model->peeraccount = '';
        $this->model->sequence = '8';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4945;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-19 16:10:39';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/19/out-998113264-305-20201019-161039-1603105839.8.wav';
        $this->model->clid = '\\\"\\\" <305>';
        $this->model->number = '';
        $this->model->dst = '998113264';
        $this->model->src = '305';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/305-00000008';
        $this->model->dstchannel = 'SIP/etc-00000009';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/998113264,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '0';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603105839.8';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '305';
        $this->model->cnam = '305';
        $this->model->outbound_cnum = '305';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603105839.8';
        $this->model->peeraccount = '';
        $this->model->sequence = '11';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4946;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-19 16:16:24';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/19/out-998113264-305-20201019-161624-1603106184.10.wav';
        $this->model->clid = '\\\"\\\" <305>';
        $this->model->number = '';
        $this->model->dst = '998113264';
        $this->model->src = '305';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/305-0000000a';
        $this->model->dstchannel = 'SIP/etc-0000000b';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/998113264,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '0';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603106184.10';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '305';
        $this->model->cnam = '305';
        $this->model->outbound_cnum = '305';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603106184.10';
        $this->model->peeraccount = '';
        $this->model->sequence = '14';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4947;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-19 16:16:42';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/19/out-905959767-305-20201019-161642-1603106202.12.wav';
        $this->model->clid = '\\\"\\\" <305>';
        $this->model->number = '';
        $this->model->dst = '905959767';
        $this->model->src = '305';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/305-0000000c';
        $this->model->dstchannel = 'SIP/etc-0000000d';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/905959767,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '0';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603106202.12';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '305';
        $this->model->cnam = '305';
        $this->model->outbound_cnum = '305';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603106202.12';
        $this->model->peeraccount = '';
        $this->model->sequence = '17';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4948;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = 2004;
        $this->model->calldate = '2020-10-19 17:27:37';
        $this->model->recordingfile = '';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '609';
        $this->model->dst = '999999999';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-00000010';
        $this->model->dstchannel = 'SIP/etc-00000011';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/999999999,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '36';
        $this->model->billsec = '21';
        $this->model->disposition = 'BUSY';
        $this->model->amaflags = '3';
        $this->model->accountcode = '2004';
        $this->model->uniqueid = '1603110457.16';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '2004';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603110457.16';
        $this->model->peeraccount = '2004';
        $this->model->sequence = '22';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4949;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = 2004;
        $this->model->calldate = '2020-10-19 17:28:13';
        $this->model->recordingfile = '';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '609';
        $this->model->dst = '999999999';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-00000010';
        $this->model->dstchannel = '';
        $this->model->lastapp = 'Busy';
        $this->model->lastdata = '20';
        $this->model->duration = '8';
        $this->model->billsec = '8';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '2004';
        $this->model->uniqueid = '1603110457.16';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '2004';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603110457.16';
        $this->model->peeraccount = '';
        $this->model->sequence = '24';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4950;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = 2007;
        $this->model->calldate = '2020-10-19 17:54:56';
        $this->model->recordingfile = '';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '609';
        $this->model->dst = '994328434';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-00000012';
        $this->model->dstchannel = 'SIP/etc-00000013';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/994328434,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '41';
        $this->model->billsec = '27';
        $this->model->disposition = 'BUSY';
        $this->model->amaflags = '3';
        $this->model->accountcode = '2007';
        $this->model->uniqueid = '1603112096.18';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '2007';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603112096.18';
        $this->model->peeraccount = '2007';
        $this->model->sequence = '25';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4951;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = 2007;
        $this->model->calldate = '2020-10-19 17:55:37';
        $this->model->recordingfile = '';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '609';
        $this->model->dst = '994328434';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-00000012';
        $this->model->dstchannel = '';
        $this->model->lastapp = 'Busy';
        $this->model->lastdata = '20';
        $this->model->duration = '20';
        $this->model->billsec = '20';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '2007';
        $this->model->uniqueid = '1603112096.18';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '2007';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603112096.18';
        $this->model->peeraccount = '';
        $this->model->sequence = '27';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4952;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 11:53:32';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-610-306-20201020-115332-1603176812.1.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '610';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-00000001';
        $this->model->dstchannel = 'SIP/610-00000002';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/610,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '23';
        $this->model->billsec = '18';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603176812.1';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603176812.1';
        $this->model->peeraccount = '';
        $this->model->sequence = '1';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4953;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 11:57:40';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-610-306-20201020-115740-1603177060.3.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '610';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-00000003';
        $this->model->dstchannel = 'SIP/610-00000004';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/610,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '4';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603177060.3';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603177060.3';
        $this->model->peeraccount = '';
        $this->model->sequence = '3';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4954;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 11:57:56';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-610-306-20201020-115756-1603177076.5.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '610';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-00000005';
        $this->model->dstchannel = 'SIP/610-00000006';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/610,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '8';
        $this->model->billsec = '3';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603177076.5';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603177076.5';
        $this->model->peeraccount = '';
        $this->model->sequence = '5';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4955;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:02:54';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-306-610-20201020-120254-1603177374.7.wav';
        $this->model->clid = '\\\"610\\\" <610>';
        $this->model->number = '';
        $this->model->dst = '306';
        $this->model->src = '610';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/610-00000007';
        $this->model->dstchannel = 'SIP/306-00000008';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/306,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '48';
        $this->model->billsec = '41';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603177374.7';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '610';
        $this->model->cnam = '610';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603177374.7';
        $this->model->peeraccount = '';
        $this->model->sequence = '7';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4956;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:10:13';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-306-600-20201020-121013-1603177813.9.wav';
        $this->model->clid = '\\\"600\\\" <600>';
        $this->model->number = '';
        $this->model->dst = '306';
        $this->model->src = '600';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/600-00000009';
        $this->model->dstchannel = 'SIP/306-0000000a';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/306,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '17';
        $this->model->billsec = '11';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603177813.9';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '600';
        $this->model->cnam = '600';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603177813.9';
        $this->model->peeraccount = '';
        $this->model->sequence = '9';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4957;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:16:14';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-306-609-20201020-121614-1603178174.11.wav';
        $this->model->clid = '\\\"609\\\" <609>';
        $this->model->number = '';
        $this->model->dst = '306';
        $this->model->src = '609';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/609-0000000b';
        $this->model->dstchannel = 'SIP/306-0000000c';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/306,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '9';
        $this->model->billsec = '3';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603178174.11';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '609';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603178174.11';
        $this->model->peeraccount = '';
        $this->model->sequence = '11';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4958;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:25:52';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/out-998909876756-609-20201020-122552-1603178752.13.wav';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '';
        $this->model->dst = '998909876756';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-0000000d';
        $this->model->dstchannel = 'SIP/etc-0000000e';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/909876756,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '5';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603178752.13';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '609';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603178752.13';
        $this->model->peeraccount = '';
        $this->model->sequence = '13';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4959;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:27:14';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/out-998909876756-609-20201020-122714-1603178834.15.wav';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '';
        $this->model->dst = '998909876756';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-0000000f';
        $this->model->dstchannel = 'SIP/etc-00000010';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/909876756,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '1';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603178834.15';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '609';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603178834.15';
        $this->model->peeraccount = '';
        $this->model->sequence = '15';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4960;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:33:23';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/out-234234234-609-20201020-123323-1603179203.17.wav';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '';
        $this->model->dst = '234234234';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-00000011';
        $this->model->dstchannel = 'SIP/etc-00000012';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/234234234,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '0';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603179203.17';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '609';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603179203.17';
        $this->model->peeraccount = '';
        $this->model->sequence = '17';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4961;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:33:30';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/out-994328434-609-20201020-123330-1603179210.19.wav';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '';
        $this->model->dst = '994328434';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-00000013';
        $this->model->dstchannel = 'SIP/etc-00000014';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/994328434,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '5';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603179210.19';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '609';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603179210.19';
        $this->model->peeraccount = '';
        $this->model->sequence = '20';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4962;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:36:30';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/out-998113264-609-20201020-123630-1603179390.21.wav';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '';
        $this->model->dst = '998113264';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-00000015';
        $this->model->dstchannel = 'SIP/etc-00000016';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/998113264,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '0';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603179390.21';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '609';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603179390.21';
        $this->model->peeraccount = '';
        $this->model->sequence = '22';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4963;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:36:38';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/out-985464165-609-20201020-123638-1603179398.23.wav';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '';
        $this->model->dst = '985464165';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-00000017';
        $this->model->dstchannel = 'SIP/etc-00000018';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/985464165,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '0';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603179398.23';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '609';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603179398.23';
        $this->model->peeraccount = '';
        $this->model->sequence = '24';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4964;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:38:22';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/out-309-306-20201020-123822-1603179502.25.wav';
        $this->model->clid = '\\\"\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '309';
        $this->model->src = '306';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/306-00000019';
        $this->model->dstchannel = 'SIP/etc-0000001a';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/309,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email^309^3';
        $this->model->duration = '0';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603179502.25';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '306';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603179502.25';
        $this->model->peeraccount = '';
        $this->model->sequence = '26';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4965;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:38:45';
        $this->model->recordingfile = '';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '';
        $this->model->dst = '998909876756';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-0000001b';
        $this->model->dstchannel = 'SIP/etc-0000001c';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/909876756,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '22';
        $this->model->billsec = '14';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '2034';
        $this->model->uniqueid = '1603179525.27';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '2034';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603179525.27';
        $this->model->peeraccount = '2034';
        $this->model->sequence = '29';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4966;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:45:49';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-600-306-20201020-124549-1603179949.29.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '600';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-0000001d';
        $this->model->dstchannel = 'SIP/600-0000001e';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/600,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '26';
        $this->model->billsec = '18';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603179949.29';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603179949.29';
        $this->model->peeraccount = '';
        $this->model->sequence = '31';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4967;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:46:29';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-600-306-20201020-124629-1603179989.31.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '600';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-0000001f';
        $this->model->dstchannel = 'SIP/600-00000020';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/600,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '18';
        $this->model->billsec = '1';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603179989.31';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603179989.31';
        $this->model->peeraccount = '';
        $this->model->sequence = '33';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4968;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:49:36';
        $this->model->recordingfile = '';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '';
        $this->model->dst = '998909809879898';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-00000021';
        $this->model->dstchannel = 'SIP/etc-00000022';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/998909809879898,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute';
        $this->model->duration = '22';
        $this->model->billsec = '15';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '2054';
        $this->model->uniqueid = '1603180176.33';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '2054';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603180176.33';
        $this->model->peeraccount = '2054';
        $this->model->sequence = '35';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4969;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:52:10';
        $this->model->recordingfile = '';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '';
        $this->model->dst = '998909809879898';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-00000023';
        $this->model->dstchannel = 'SIP/etc-00000024';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/998909809879898,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute';
        $this->model->duration = '21';
        $this->model->billsec = '12';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '2055';
        $this->model->uniqueid = '1603180330.35';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '2055';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603180330.35';
        $this->model->peeraccount = '2055';
        $this->model->sequence = '37';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4970;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = 2057;
        $this->model->calldate = '2020-10-20 12:54:34';
        $this->model->recordingfile = '';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '';
        $this->model->dst = '998909878898';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-00000026';
        $this->model->dstchannel = 'SIP/etc-00000027';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/909878898,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '39';
        $this->model->billsec = '24';
        $this->model->disposition = 'BUSY';
        $this->model->amaflags = '3';
        $this->model->accountcode = '2057';
        $this->model->uniqueid = '1603180474.38';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '2057';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603180474.38';
        $this->model->peeraccount = '2057';
        $this->model->sequence = '40';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4971;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = 2057;
        $this->model->calldate = '2020-10-20 12:55:13';
        $this->model->recordingfile = '';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '';
        $this->model->dst = '998909878898';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-00000026';
        $this->model->dstchannel = '';
        $this->model->lastapp = 'Busy';
        $this->model->lastdata = '20';
        $this->model->duration = '20';
        $this->model->billsec = '20';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '2057';
        $this->model->uniqueid = '1603180474.38';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '2057';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603180474.38';
        $this->model->peeraccount = '';
        $this->model->sequence = '42';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4972;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = 2056;
        $this->model->calldate = '2020-10-20 12:55:41';
        $this->model->recordingfile = '';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '6541564';
        $this->model->dst = '998909876756';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-00000028';
        $this->model->dstchannel = 'SIP/etc-00000029';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/909876756,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '15';
        $this->model->billsec = '8';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '2056';
        $this->model->uniqueid = '1603180541.40';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '2056';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603180541.40';
        $this->model->peeraccount = '2056';
        $this->model->sequence = '43';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4973;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 12:59:22';
        $this->model->recordingfile = '';
        $this->model->clid = '\\\"\\\" <712078030>';
        $this->model->number = '';
        $this->model->dst = '998909876756';
        $this->model->src = '712078030';
        $this->model->dcontext = 'from-internal';
        $this->model->channel = 'SIP/609-0000002a';
        $this->model->dstchannel = 'SIP/etc-0000002b';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/etc/909876756,300,Tb(func-apply-sipheaders^s^1,(1))U(sub-send-obroute-email';
        $this->model->duration = '16';
        $this->model->billsec = '8';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '2034';
        $this->model->uniqueid = '1603180762.42';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '2034';
        $this->model->cnam = '609';
        $this->model->outbound_cnum = '712078030';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603180762.42';
        $this->model->peeraccount = '2034';
        $this->model->sequence = '45';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4974;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 14:22:16';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-600-306-20201020-142216-1603185736.46.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '600';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-0000002e';
        $this->model->dstchannel = 'SIP/600-0000002f';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/600,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '14';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603185736.46';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603185736.46';
        $this->model->peeraccount = '';
        $this->model->sequence = '49';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4975;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 14:25:02';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-600-306-20201020-142502-1603185902.48.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '600';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-00000030';
        $this->model->dstchannel = 'SIP/600-00000031';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/600,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '25';
        $this->model->billsec = '21';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603185902.48';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603185902.48';
        $this->model->peeraccount = '';
        $this->model->sequence = '51';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4976;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 14:26:42';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-600-306-20201020-142642-1603186002.50.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '600';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-00000032';
        $this->model->dstchannel = 'SIP/600-00000033';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/600,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '24';
        $this->model->billsec = '12';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603186002.50';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603186002.50';
        $this->model->peeraccount = '';
        $this->model->sequence = '53';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4977;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 14:28:31';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-600-306-20201020-142831-1603186111.52.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '600';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-00000034';
        $this->model->dstchannel = 'SIP/600-00000035';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/600,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '174';
        $this->model->billsec = '169';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603186111.52';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603186111.52';
        $this->model->peeraccount = '';
        $this->model->sequence = '55';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4978;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 14:31:29';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-600-306-20201020-143129-1603186289.54.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '600';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-00000036';
        $this->model->dstchannel = 'SIP/600-00000037';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/600,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '60';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603186289.54';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603186289.54';
        $this->model->peeraccount = '';
        $this->model->sequence = '57';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4979;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 14:32:46';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-600-306-20201020-143247-1603186366.56.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '600';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-00000038';
        $this->model->dstchannel = 'SIP/600-00000039';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/600,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '15';
        $this->model->billsec = '0';
        $this->model->disposition = 'BUSY';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603186366.56';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603186366.56';
        $this->model->peeraccount = '';
        $this->model->sequence = '60';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4980;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 14:35:40';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-600-306-20201020-143540-1603186539.58.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '600';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-0000003a';
        $this->model->dstchannel = 'SIP/600-0000003b';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/600,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '41';
        $this->model->billsec = '38';
        $this->model->disposition = 'ANSWERED';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603186539.58';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603186539.58';
        $this->model->peeraccount = '';
        $this->model->sequence = '63';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4981;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 14:38:02';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-600-306-20201020-143802-1603186682.60.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '600';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-0000003c';
        $this->model->dstchannel = 'SIP/600-0000003d';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/600,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '60';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603186682.60';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603186682.60';
        $this->model->peeraccount = '';
        $this->model->sequence = '65';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4982;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = null;
        $this->model->calldate = '2020-10-20 14:43:45';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-609-306-20201020-144345-1603187025.62.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '609';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-0000003e';
        $this->model->dstchannel = 'SIP/609-0000003f';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/609,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '12';
        $this->model->billsec = '0';
        $this->model->disposition = 'BUSY';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603187025.62';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603187025.62';
        $this->model->peeraccount = '';
        $this->model->sequence = '68';
        $this->save();


        $this->model = new CallsCdr();

        $this->model->id = 4983;
        $this->model->sort = null;
        $this->model->name = '';
        $this->model->title = '';
        $this->model->tranz = null;
        $this->model->accept = null;
        $this->model->active = 1;
        $this->model->shop_order_id = 2091;
        $this->model->calldate = '2020-10-20 14:46:05';
        $this->model->recordingfile = '/audioz/mplace/call/2020/10/20/internal-609-306-20201020-144605-1603187165.64.wav';
        $this->model->clid = '\\\"306\\\" <306>';
        $this->model->number = '';
        $this->model->dst = '609';
        $this->model->src = '306';
        $this->model->dcontext = 'ext-local';
        $this->model->channel = 'SIP/306-00000040';
        $this->model->dstchannel = 'SIP/609-00000041';
        $this->model->lastapp = 'Dial';
        $this->model->lastdata = 'SIP/609,,HhTtrb(func-apply-sipheaders^s^1)';
        $this->model->duration = '10';
        $this->model->billsec = '0';
        $this->model->disposition = 'NO ANSWER';
        $this->model->amaflags = '3';
        $this->model->accountcode = '';
        $this->model->uniqueid = '1603187165.64';
        $this->model->userfield = '';
        $this->model->did = '';
        $this->model->cnum = '306';
        $this->model->cnam = '306';
        $this->model->outbound_cnum = '';
        $this->model->outbound_cnam = '';
        $this->model->dst_cnam = '';
        $this->model->linkedid = '1603187165.64';
        $this->model->peeraccount = '';
        $this->model->sequence = '71';
        $this->save();


    }

}
