<?php

namespace zetsoft\inserts\arbit;

use zetsoft\system\actives\ZInsert;
use zetsoft\system\Az;
use zetsoft\system\kernels\ZMigration;
use zetsoft\models\user\User;

class UserInsert extends ZInsert
{

    public function run()
    {

        $this->model = new User();

        $this->model->id = 304;
        $this->model->sort = null;
        $this->model->name = 'user4132,,usern@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user4132';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'usern@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-09-21 12:24:44';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'pWZggD9ARC5wKZmBxvbjuXYaaum4CYzD23qYDxsHgjUthzza3v4eBSrWUkPdM5vW';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 294;
        $this->model->sort = null;
        $this->model->name = 'user1586,';
        $this->model->guid = '';
        $this->model->title = 'user1586';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = 'bcb15f821479b4d5772bd0ca866c00ad5f926e3580720659cc80d39c9d09802a';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '998907654534';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'MEzRTaPxSSnGUywbS5VVbPfPS8BUz88UPcyjs7mF4e8VTb6vGrArMvR97nEBfKJW';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 290;
        $this->model->sort = null;
        $this->model->name = 'user3968,';
        $this->model->guid = '';
        $this->model->title = 'user3968';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = 'a320480f534776bddb5cdb54b1e93d210a3c7d199e80a23c1b2178497b184c76';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '123321';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-08-25 09:08:03';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'jwVkrUBQh8WRMAgRQHMsa358JyGvyN7zaKGwZnTN5keqUjWxbcse8bypkkcWKUNx';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 298;
        $this->model->sort = null;
        $this->model->name = 'user4386,,mail@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user4386';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = 'bcb15f821479b4d5772bd0ca866c00ad5f926e3580720659cc80d39c9d09802a';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'mail@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'ucwgCkAUu52856kHynkfcTzgDyNRAapf8jQqe7e43U9zMnA8DxWFHP6dNq62BDCm';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 300;
        $this->model->sort = null;
        $this->model->name = 'user3121,,admins@gmail.ru';
        $this->model->guid = '';
        $this->model->title = 'user3121';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = 'bcb15f821479b4d5772bd0ca866c00ad5f926e3580720659cc80d39c9d09802a';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'admins@gmail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'QvvRPFgcbfbFXZn9kDaXQUnMn7Te8dzdHPSnU8ZuWQKVRk3psDC5br57BVEtYrEs';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 321;
        $this->model->sort = null;
        $this->model->name = 'user3273,,user@mail.uz';
        $this->model->guid = '';
        $this->model->title = 'user3273';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'user@mail.uz';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'vbwkUZ3yUdwAp6UAY5YTsMGzvfDP4hUc8FNq85aMTC8Ns3pM47kDURmVbKycdV8G';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 324;
        $this->model->sort = null;
        $this->model->name = 'user3834,,dilshod@inbox.ru';
        $this->model->guid = '';
        $this->model->title = 'user3834';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'dilshod@inbox.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-08-29 15:38:59';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'bPPA4R6kx8Ghev37j6PFunENpzJzPcPHQEgF6SeFZep5pFuxCtWF3jvyNnFAcUPK';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 311;
        $this->model->sort = null;
        $this->model->name = 'user7305,,mail@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user7305';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = 'bcb15f821479b4d5772bd0ca866c00ad5f926e3580720659cc80d39c9d09802a';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'mail@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'guq3Xj2E8myup3CaPSCG85n7UhJeuBPredXffry37RpBg7GkeMHSQMYYqDcr7hSk';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 313;
        $this->model->sort = null;
        $this->model->name = 'user9118,,john@mail.com';
        $this->model->guid = '';
        $this->model->title = 'user9118';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'john@mail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-08-25 18:24:23';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'EF9FrQua8qWZVPMj9u27z96qKUKUudBukqYXgD4mEMQeYQHMz2QaeAuYcrgPJEzF';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 303;
        $this->model->sort = null;
        $this->model->name = 'user7334,,usern@gmail.co';
        $this->model->guid = '';
        $this->model->title = 'user7334';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'usern@gmail.co';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-08-25 12:46:05';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'R7c3ZgSAqCh5KtuKbrAfrCdm3tk5QA8epbKUpkMWw8sbsGFbRVxGVG8CfWJKQA8e';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 308;
        $this->model->sort = null;
        $this->model->name = 'user3150,,dilshodw22@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user3150';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'dilshodw22@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'rQ7Gc87KdNFJt2exYDDHd2TDbjwwBmR6wqsHb7x8MhY5Em5kqzyzG78YcQd7pzMW';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 306;
        $this->model->sort = null;
        $this->model->name = 'user504,,dilshodw@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user504';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'dilshodw@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'qaKQEBmQ3Yb7ZMNNKaRAmwZvtBKrQ3vCa94GFYPBPQVjBZ2SpwREX4TJZUv5W6XW';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 314;
        $this->model->sort = null;
        $this->model->name = 'user6649,,user@inbox.ru';
        $this->model->guid = '';
        $this->model->title = 'user6649';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'user@inbox.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'N2XxeNftzMF5fCBZG5arj4fBHh7VAf9SV9mKm9CGwvhXnYEe4wQZGb8JR4EaXZ9g';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 312;
        $this->model->sort = null;
        $this->model->name = 'user6773,,john.jphn@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user6773';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'john.jphn@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'r6ST2T5M7Avjwy2cPhHu6ZhNxhdtWbS4P7X9D3vabUzajQ6GXG2MsJu9tzV3t595';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 307;
        $this->model->sort = null;
        $this->model->name = 'user3627,,dilshodw2@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user3627';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'dilshodw2@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'RS2r7AjARM4RqYhWZ7dp9rjHcGRAKqYerZvWHNwpV32MfcsQQ4Xr9ccZf5GaZbKj';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 289;
        $this->model->sort = null;
        $this->model->name = 'user7407,,admin@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user7407';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'admin@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-08-29 15:30:49';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'dcparfvnXTYwH7KwWtuVvDWWENsYmRxdXuwDFCfaxGhgjySeE72mfQTXPdXycmzs';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 305;
        $this->model->sort = null;
        $this->model->name = 'user3955,,dilshod@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user3955';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'dilshod@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-08-31 10:03:27';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'vGbJxjMynFhxDNR5VrAagbx9KsqERupXAJtT5frqDUgYU4tCvsk399B386ybKuXK';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = [
            'nomer' => '',
            'expiry' => '',
        ];
        $this->save();


        $this->model = new User();

        $this->model->id = 310;
        $this->model->sort = null;
        $this->model->name = 'user9715,,adm@mail.uz';
        $this->model->guid = '';
        $this->model->title = 'user9715';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'adm@mail.uz';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-08-25 13:41:08';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'WBWVBfgH4a7rNyJjhfGvYJCyP2eDDbg28Euhn7vM93KSS5eeEvFcY9qGqHpCmMtX';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 315;
        $this->model->sort = null;
        $this->model->name = 'user3837,,user@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user3837';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'user@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'AaPG8uPACyh5K2cqrHqGN83eGdS38ct85j2YU9eUwc2jJMyazADy9h3sPTSDGP6W';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 292;
        $this->model->sort = null;
        $this->model->name = 'user4962,,admin@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user4962';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'admin@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'Vg972XcBy9yZY5AUqn2M7dQj7D25yTtUQ7pN9degtHMNMWmxh5HAJh4znbJz77V9';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 357;
        $this->model->sort = null;
        $this->model->name = 'user1883,,shahruh84@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user1883';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '0b1696b4ac57e9b4edb4291f136b74487da9586cff00d8c0f7c865770b3b0888';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'shahruh84@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-09-21 12:50:41';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'amYbSNTWnKdnsqAaD3rGuwTSWw8RGKTKDwpBjakvfYeHvgpDYtRkfY8e9dX3Yd5t';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 318;
        $this->model->sort = null;
        $this->model->name = 'user7840,';
        $this->model->guid = '';
        $this->model->title = 'user7840';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '1234566';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'YSttn7dgf2q5r5PAaTrhUTd6pdDuC6Hbb8CsA4v39S7rqeW5KzqBfvqTKHJezekg';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 374;
        $this->model->sort = null;
        $this->model->name = ',,jakh.kudratoff@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user7680';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'jakh.kudratoff@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '87a749770a7eb212eefbea6aa3bc95b85b82fe2b6adc47bc6d34d1bde6bb3f2e';
        $this->model->verified_email = null;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'jQjYVTgsNzKqT9Kqe9ZhJbK3ENe9ZNYSZm4jftwNykkcNpqECwdfeqAJ7vu7W5Ca';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 319;
        $this->model->sort = null;
        $this->model->name = 'user413,,sas@sdad.sad';
        $this->model->guid = '';
        $this->model->title = 'user413';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'sas@sdad.sad';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-08-25 21:17:26';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = '8qU4kfc8meBBmvhUcMfvwM6JCGxKcHaCFnP4KRHnJApHQz4rUUXrDRyDYaPRnV5z';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 323;
        $this->model->sort = null;
        $this->model->name = 'user4358,,user@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user4358';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'user@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'EsKc3ru2fSpjvUqDcGrmfSyzc9EbVF7TK4RnTZnjQSahqgduzZxSABhZ6npE9kg2';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 331;
        $this->model->sort = null;
        $this->model->name = 'user7490,,new.mailcom@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user7490';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'new.mailcom@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '4823';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'yddksFt4pbJbKx3uEKXz2VvJrp7KeUktryq9AKxCEG8XbS6k2ujTa5zfm9yA62Ju';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 333;
        $this->model->sort = null;
        $this->model->name = 'user4700,,mailmail@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user4700';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '3ea87a56da3844b420ec2925ae922bc731ec16a4fc44dcbeafdad49b0e61d39c';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'mailmail@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '7645';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'RM67Nd8JRtYNwmzQSDXGbEtTXaqpjaG6MywtZcezWj76J72UckJkXBrnM5AVjGFh';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 325;
        $this->model->sort = null;
        $this->model->name = 'user3899,';
        $this->model->guid = '';
        $this->model->title = 'user3899';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = 'bcb15f821479b4d5772bd0ca866c00ad5f926e3580720659cc80d39c9d09802a';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '998909427077';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'zQMGt9uYvgwd7BmqMhNHy9wmYMkDQP8BQvExSG3CVuS3axRk4st68t3yqhJF6skd';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 317;
        $this->model->sort = null;
        $this->model->name = 'user6495,,daho@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user6495';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'daho@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-09-01 12:01:43';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'tgXMPK2pFbe4NrXhC646vqtwhDvzVfC9EU6xac3ECscDWCTV49ma4XFWPG6Wr3wH';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 326;
        $this->model->sort = null;
        $this->model->name = 'user520,,mmail@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user520';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = 'bcb15f821479b4d5772bd0ca866c00ad5f926e3580720659cc80d39c9d09802a';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'mmail@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-08-31 17:18:43';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'MDSzDBmUDntjEVd9ByVkJzkpM9S5RSumXwarSM2hkg7bhanfRwwuqk3G4pFFC59m';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 327;
        $this->model->sort = null;
        $this->model->name = 'user6918,,mail.mail@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user6918';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = 'bcb15f821479b4d5772bd0ca866c00ad5f926e3580720659cc80d39c9d09802a';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'mail.mail@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = '2WwPDZs2QZjKx5yqwus9YDmvuFX8xBjNsNkCxw2SD6vRU28FpdcRp8v9shTqCY3y';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 328;
        $this->model->sort = null;
        $this->model->name = 'user4469,,mmail.mail@mail.com';
        $this->model->guid = '';
        $this->model->title = 'user4469';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = 'bcb15f821479b4d5772bd0ca866c00ad5f926e3580720659cc80d39c9d09802a';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'mmail.mail@mail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'kkJ6EuzxwxPNwuPDTkvhzpjTbAsMQfPXU8uupamYXhFxqhDkaFUKjh5V7qvk4MrF';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 329;
        $this->model->sort = null;
        $this->model->name = 'user5970,,new@mail.com';
        $this->model->guid = '';
        $this->model->title = 'user5970';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = 'bcb15f821479b4d5772bd0ca866c00ad5f926e3580720659cc80d39c9d09802a';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'new@mail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'JCwJpzRDmFYv76NBzaUfkWffphc7wkGzesdzCrNGCazptyTPPku7XGypNS7Ugnyh';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 332;
        $this->model->sort = null;
        $this->model->name = 'user9156,,jakudratov@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user9156';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = 'bcb15f821479b4d5772bd0ca866c00ad5f926e3580720659cc80d39c9d09802a';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'jakudratov@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '2768';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'CZ4atpEcbww4CDQDuSpYZCeJS2KWqeNMemdx5TkxXJNugdp9DUw4frc2mKTBfKYm';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 293;
        $this->model->sort = null;
        $this->model->name = 'user8604,';
        $this->model->guid = '';
        $this->model->title = 'user8604';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '998909876543';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'Y9Z3cXhJ6XfxTbPC8jJgtsEaVVJnJBYARe29H7AZMTjwuNwhbas77FrhygmGeJcR';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 302;
        $this->model->sort = null;
        $this->model->name = 'user182,,ad@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user182';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'admin';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'ad@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-09-18 13:19:56';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '1';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'EH7UpM8h72b7wbyVFJwGFxaCcHVKyNhEApyS3EHQmVjzSnPzK8w5zaVURCRNKCX7';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 344;
        $this->model->sort = null;
        $this->model->name = 'user6128,,kemakeldi99@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user6128';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '814f12133e6ab3d77e96aae2ad00c355dd1c8d1d783ddbbd772e18cc50775d6c';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'kemakeldi99@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'yRaWcQbFGmk8xvHShyMZ2yEN6Cd7MCD39qZk2V2Mg9VgqxpFspfS7yxwu2habUxS';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 347;
        $this->model->sort = null;
        $this->model->name = 'user8459,,qrqwrwqr@qw.qw';
        $this->model->guid = '';
        $this->model->title = 'user8459';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'qrqwrwqr@qw.qw';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = 'a435c931f85b2a24067aebf8c7782762ee8d29bfed205718dc63d977faeef7f8';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'uNr7Yeg4n6D9FSmKt3y45FynA6Ny8mFwCv4cpp4VChdKB6e8YtQNB7z57fdyWYtE';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 291;
        $this->model->sort = null;
        $this->model->name = 'user7100,';
        $this->model->guid = '';
        $this->model->title = 'user7100';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = 'a320480f534776bddb5cdb54b1e93d210a3c7d199e80a23c1b2178497b184c76';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '998971410690';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'vjnf7verB8THDbdsFBB3hS7m2FvbrsHGKET5XuApzHp4VtHxns6AtMv5bF6p9UjJ';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 316;
        $this->model->sort = null;
        $this->model->name = 'user3119,';
        $this->model->guid = '';
        $this->model->title = 'user3119';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8bb0cf6eb9b17d0f7d22b456f121257dc1254e1f01665370476383ea776df414';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '1234567';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'PNCXxJY4CAUR58n97mGGNVnBJwZfBkmMBdfQ3N9MFaSEKpxBM7Re9mn259CcNJNA';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 296;
        $this->model->sort = null;
        $this->model->name = 'user925,male';
        $this->model->guid = '';
        $this->model->title = 'user925';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'user';
        $this->model->gender = 'male';
        $this->model->lang = '';
        $this->model->phone = '98-392-83-29';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'GnYgvgxmVXvqgRzjkjCkbtwbDp2ez6UEySrd9s9ktRAH2mUwXSRqX4R8TWz7bzhd';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = [
            '24',
        ];
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = [
            'github' => '',
            'twitter' => '',
            'facebook' => '',
            'telegram' => '',
            'linked_in' => '',
            'google_plus' => '',
        ];
        $this->save();


        $this->model = new User();

        $this->model->id = 322;
        $this->model->sort = null;
        $this->model->name = 'user908,,newuser@mail.com';
        $this->model->guid = '';
        $this->model->title = 'user908';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'user';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'newuser@mail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = '2rjFQeh9mwfamjTPDzFs7eB6rADufPDpSvCWfZcKeprwFqN5BEB3mfPcqNRu6Qsh';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 343;
        $this->model->sort = null;
        $this->model->name = 'user3897,male';
        $this->model->guid = '';
        $this->model->title = 'user3897';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'user';
        $this->model->gender = 'male';
        $this->model->lang = 'uz';
        $this->model->phone = '99-897-40-12';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-09-09 11:53:17';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'WuZ6dyuZuRjpjczWSqg4CEkjrSC4WWx94vS8emrcpYxHqVMAxV28BMuuZWPKA8hu';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = [
            '63',
        ];
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = [
            'github' => '',
            'twitter' => '',
            'facebook' => '',
            'telegram' => '',
            'linked_in' => '',
            'google_plus' => '',
        ];
        $this->save();


        $this->model = new User();

        $this->model->id = 351;
        $this->model->sort = null;
        $this->model->name = 'user564,,abdulloh.tursunaliyev77@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user564';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'admin';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'abdulloh.tursunaliyev77@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-09-18 15:43:15';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'EsyXqVwtMZQJ8uKh9CeTmtkzhsQ3CRPN5C9nMMrWah7P9zZwVtehc9P8GDZusckW';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 354;
        $this->model->sort = null;
        $this->model->name = 'user2011,,murodov.mirbosit@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user2011';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'murodov.mirbosit@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = 'c25cdcf313b411b8baebf7829f0f07c2c847531fa3f45f7084b956a6c206f9a7';
        $this->model->verified_email = null;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'txuqPEQtc5QC2xNcFCGuUBPhbR7jfUtgRZeA2nHjNZNZKMgBYCWHfHGE7rX8wEYc';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 358;
        $this->model->sort = null;
        $this->model->name = 'user6338,,shahruh8484@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user6338';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '0b1696b4ac57e9b4edb4291f136b74487da9586cff00d8c0f7c865770b3b0888';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'shahruh8484@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-09-21 15:45:42';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'E8DQRRu4eV9K68fpcBSbc9Ud7PTCdBcDS73AU34xGD5AWnTr7X6CaCDzT9Sdv7wR';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 352;
        $this->model->sort = null;
        $this->model->name = 'user9225,,shaxboz.israilov@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user9225';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '9c6c0d9d6209775f9f9510e179b057a93788103b2ee05b350b27ebf1bec01bd1';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'shaxboz.israilov@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = 'a7b4b98169a7b8ecf89c1d27961cd1b37e5b1c721577dae9883ce7f9ea8a4186';
        $this->model->verified_email = null;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'H6vuRfXcv8SdZYhwHsfmt5x9svuGvvJB5X356zRQqThfMNkgtTJnTw9P36Syx86N';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 353;
        $this->model->sort = null;
        $this->model->name = 'user1582,';
        $this->model->guid = '';
        $this->model->title = 'user1582';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '998935699922';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = '';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '7126';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'bscvs3gPR5WEbGsDf7ad9Kbx9E6Yhk6brWe4R4D2fdMfjQXB7ZVyMD6bFZDnuGyM';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 355;
        $this->model->sort = null;
        $this->model->name = 'user2107,,test@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user2107';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '37268335dd6931045bdcdf92623ff819a64244b53d0e746d438797349d4da578';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'test@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '05b13bc2eccb21f13edc51027d1de059f5691d135f8884234106068291f23586';
        $this->model->verified_email = null;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'MDmFbMHjd6UeRTU9NZmgD49HBWdthCg6SyX9TuXPEnd3rtmEVbHP8GWz24QWhvZk';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 370;
        $this->model->sort = null;
        $this->model->name = 'user2739,,bohodirrahmedov011@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user2739';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = 'ab4d7ebb5f36d630984e0d0c2b0c5309203251fa7d64a5b4fd61cf88bcbed3dc';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'bohodirrahmedov011@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'FVt6SrbvqeRCuhgHVjegEKbKDTMgPTcx6wxY9xMYNFPy5AVTy5w46sSZdhVSWAJ2';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 299;
        $this->model->sort = null;
        $this->model->name = 'user9560,,admin@gmail.ru';
        $this->model->guid = '';
        $this->model->title = 'user9560';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = 'bcb15f821479b4d5772bd0ca866c00ad5f926e3580720659cc80d39c9d09802a';
        $this->model->role = 'admin';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = 0;
        $this->model->extpass = null;
        $this->model->email = 'admin@gmail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-09-30 15:04:27';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = 0;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'pYG3CF2cYSfum2frRWWfMdJNcKKFAsJxeAV2zGsUuKACgkNFEsKQxAXy9k8p5S4q';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 341;
        $this->model->sort = null;
        $this->model->name = 'jahongir,,jakh.kudratov@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'jahongir';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'admin';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'jakh.kudratov@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-10-02 19:38:09';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = 1000;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'qvhFgB9YC4UUHfZNG6Pd8WZ6k7H6waw5Vg2UeAXJgKe44fFxSwzStCMQ3jmv2gtz';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = [
            'github' => '',
            'twitter' => '',
            'facebook' => '',
            'telegram' => '',
            'linked_in' => '',
            'google_plus' => '',
        ];
        $this->save();


        $this->model = new User();

        $this->model->id = 346;
        $this->model->sort = null;
        $this->model->name = 'user5643,,nshaxrizod@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user5643';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92';
        $this->model->role = 'admin';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'nshaxrizod@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-10-03 11:43:41';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = 80;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = 1;
        $this->model->auth_key = 'gFrjVzcy7pYzNRz9mhEKHEXBEyArzWaFaFsN4TtK3UvnnJ6bz3GkMMJyU9Act2DJ';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 368;
        $this->model->sort = null;
        $this->model->name = 'user7247,,spec7575@mail.ru';
        $this->model->guid = '';
        $this->model->title = 'user7247';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '06bc0a1a46cc6199f779727073996896b97c48bf10ae9198d204936310963dc0';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'spec7575@mail.ru';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = '';
        $this->model->lastseen = null;
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = null;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = '6TNugsT92b2nGv8EMKyecfVPzDZbfBfuvYRAkuR8WTF7bHsKxqk8Am6VvBfcYsTD';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = "";
        $this->save();


        $this->model = new User();

        $this->model->id = 350;
        $this->model->sort = null;
        $this->model->name = 'user278,,dilshodjon.gb@gmail.com';
        $this->model->guid = '';
        $this->model->title = 'user278';
        $this->model->tranz = null;
        $this->model->active = 1;
        $this->model->password = '96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e';
        $this->model->role = 'client';
        $this->model->gender = '';
        $this->model->lang = '';
        $this->model->phone = '';
        $this->model->number = null;
        $this->model->extpass = null;
        $this->model->email = 'dilshodjon.gb@gmail.com';
        $this->model->website = '';
        $this->model->photo = "";
        $this->model->status = 'online';
        $this->model->lastseen = '2020-10-01 19:11:19';
        $this->model->blocked = null;
        $this->model->apiclient = null;
        $this->model->place_region_id = null;
        $this->model->balance = 190;
        $this->model->autodial = null;
        $this->model->purchase_count = null;
        $this->model->verify_code = '0';
        $this->model->verified_email = 1;
        $this->model->verified_phone = null;
        $this->model->auth_key = 'Y3mwJQsQDfwMpUXNd3kwd5fjY7MTjSE8Kmz2bhZYPn5Bgxe7nqyEyStY2x73ube2';
        $this->model->oauth = "";
        $this->model->oauth_type = '';
        $this->model->user_company_id = null;
        $this->model->place_adress_ids = "";
        $this->model->currency = '';
        $this->model->referal_link = '';
        $this->model->social = [
            'github' => '',
            'twitter' => '',
            'facebook' => '',
            'telegram' => '',
            'linked_in' => '',
            'google_plus' => '',
        ];
        $this->save();


    }

}
