<?php
/**
 *
 *
 * Author:  Asror Zakirov
 * https://www.linkedin.com/in/asror-zakirov
 * https://www.facebook.com/asror.zakirov
 * https://github.com/asror-z
 *
 */

namespace zetsoft\system\assets;


interface ZColor
{

    public const parents = [
        'multiwidget' => 'multiwidget',
        'formwidget' => 'formwidget',
    ];

    public const shadows = [
        'z-depth-1' => 'z-depth-1',
        'z-depth-1-half' => 'z-depth-1-half',
        'z-depth-2' => 'z-depth-2',
        'z-depth-3' => 'z-depth-3',
        'z-depth-4' => 'z-depth-4',
        'z-depth-5' => 'z-depth-5'
    ];

    public const iconSize = [
        '0' => 'fa-0',
        '1x' => 'fa-1x',
        '2x' => 'fa-2x',
        '3x' => 'fa-3x',
        '4x' => 'fa-4x',
        '5x' => 'fa-5x',
    ];

    public const textColor = [
        //Material text color
       'text-default'  => 'text-default',
       'text-primary'  => 'text-primary',
       'text-secondary'=> 'text-secondary',
       'text-success'  => 'text-success',
       'text-danger'   => 'text-danger',
       'text-warning'  => 'text-warning',
       'text-info'     => 'text-info',
       'text-green-main' => 'text-green-main',

       //Basic text color
        'text-light'  => 'text-light',
        'text-dark'   => 'text-dark',
        'text-body'   => 'text-body',
        'text-muted'  => 'text-muted',
        'text-white'  => 'text-white',
        'text-black-50' => 'text-black-50',
        'text-white-50' => 'text-white-50',

        //Additional color
        'red-text'  => 'red-text',
        'pink-text'  => 'pink-text',
        'purple-text'=> 'purple-text',
        'deep-purple-text'  => 'deep-purple-text',
        'indigo-text'   => 'indigo-text',
        'blue-text'  => 'blue-text',
        'light-blue-text'     => 'light-blue-text',
        'cyan-text'  => 'cyan-text',
        'teal-text'  => 'teal-text',
        'green-text'=> 'green-text',
        'light-green-text'  => 'light-green-text',
        'lime-text'   => 'lime-text',
        'yellow-text'  => 'yellow-text',
        'amber-text'  => 'amber-text',
        'orange-text'  => 'orange-text',
        'deep-orange-text'=> 'deep-orange-text',
        'brown-text'  => 'brown-text',
        'grey-text'   => 'grey-text',
        'blue-grey-text'  => 'blue-grey-text',
    ];

    public const badgeType = [
        'badge-default' => 'badge-default',
        'badge-primary' => 'badge-primary',
        'badge-secondary' => 'badge-secondary',
        'badge-success' => 'badge-success',
        'badge-danger' => 'badge-danger',
        'badge-warning' => 'badge-warning',
        'badge-info' => 'badge-info',
        'badge-light' => 'badge-light',
        'badge-dark' => 'badge-dark',
    ];

    public const btnSize = [
        'btn-lg' => 'btn-lg',
        'btn-md' => 'btn-md',
        'btn-sm' => 'btn-sm',
        'btn-micro' => 'btn-micro',
        'btn-mini' => 'btn-mini',
        'btn-manual' => 'btn-manual',
        'default' => 'default'
    ];

    public const theme = [
        'greenTheme' => 'greenTheme',
        'darkTheme' => 'darkTheme',
        'lightTheme' => 'lightTheme',
        'default' => 'default'
    ];

    /**
     *
     * Tooltip
     */

    public const ttSide = [
        'top' => 'top',
        'bottom' => 'bottom',
        'right' => 'right',
        'left' => 'left',
        'top-left' => 'top-left',
        'bottom-left' => 'bottom-left',
        'top-right' => 'top-right',
        'bottom-right' => 'bottom-right',
    ];

    public const ttSize = [
        'default' => 'default',
        'large' => 'large',
        'medium' => 'medium',
        'small' => 'small'
    ];

    public const ttColor = [
        'default' => 'default',
        'info' => 'info',
        'success' => 'success',
        'warning' => 'warning',
        'error' => 'error'
    ];

    public const ttAnimate = [
        'default' => 'default',
        'bounce' => 'bounce',
        'no-animate' => 'no-animate'
    ];

    public const method = [
        'none' => '',
        'get' => 'get',
        'post' => 'post',
    ];

    /**
     *
     * Core Datas
     */

    public const color = [
        'none' => '',

        // Bootstrap

        'danger-color' => 'danger-color',
        'success' => 'success',
        'muted' => 'muted',
        'warning-color' => 'warning-color',
        'success-color' => 'success-color',
        'success-color-dark' => 'success-color-dark',
        'info-color' => 'info-color',
        'info-color-dark' => 'info-color-dark',
        'danger-color-dark' => 'danger-color-dark',
        'warning-color-dark' => 'warning-color-dark',

        // Color MDB

        'default-color' => 'default-color',
        'default-color-dark' => 'default-color-dark',
        'primary-color' => 'primary-color',
        'primary-color-dark' => 'primary-color-dark',
        'secondary-color' => 'secondary-color',
        'secondary-color-dark' => 'secondary-color-dark',

        //Dark theme

        'elegant-color' => 'elegant-color',
        'stylish-color' => 'stylish-color',
        'stylish-color-dark' => 'stylish-color-dark',
        'unique-color' => 'unique-color',
        'unique-color-dark' => 'unique-color-dark',
        'special-color' => 'special-color',
        'special-color-dark' => 'special-color-dark',

        //Palette

        'red' => 'red',
        'pink' => 'pink',
        'deep-purple' => 'deep-purple',
        'indigo' => 'indigo',
        'light-blue' => 'light-blue',
        'cyan' => 'cyan',
        'teal' => 'teal',
        'green' => 'green',
        'light-green' => 'light-green',
        'lime' => 'lime',
        'limegreen' => 'limegreen',
        'yellow' => 'yellow',
        'amber' => 'amber',
        'orange' => 'orange',
        'deep-orange' => 'deep-orange',
        'brown' => 'brown',
        'grey' => 'grey',
        'blue-grey' => 'blue-grey',
        'blue' => 'blue',
        'black' => 'black',
        'mdb-color' => 'mdb-color',
        'white' => 'white',
        'deeppink' => 'deeppink',
        'hotpink' => 'hotpink',
        'lightpink' => 'lightpink',

        /**
         *
         * Feruza
         */
        'dhggfef'=> '#f3f3f3',
        'acajou' => '#563727',
        'burgundy' => '#372C2E',
        'curcum' => '#DE9E48',
        'bronze' => '#DAB692',
        'russet' => '#7A431D',
        'glitter' => '#E7E9F0',
        'oxford-blue' => '#051747',
        'payne-grey' => '#535F80',
        'royal-blue' => '#0d5adb',
        'pale-gold' => '#C0B283',
        'silk' => '#dad2b7',
        'paper' => '#f5f3eb',
        'charcoal' => '#3a341e',
        'crimson' => '#6F52ED',
        'indigo-blue' => '#373B53',
        'ultramarine' => '#3B3F59',
        'modern-blue' => '#626682',
        'indigo-text' => '#969CBA',
        'lighten-blue' => '#c2d5f2',
        'light-grey' => '#f0f0fa',
        'medium-blue' => '#005ecb',
        'green-special' => '#53b929',
        'green-phone' => '#00c851;',
        'main-green' => '#10b410',

        //RGBA
        'rgba-blue-light' => 'rgba-blue-light',
        'rgba-red-light' => 'rgba-red-light',
        'rgba-pink-light' => 'rgba-pink-light',
        'rgba-purple-light' => 'rgba-purple-light',
        'rgba-indigo-light' => 'rgba-indigo-light',
        'rgba-cyan-light' => 'rgba-cyan-light',
        'rgba-orange-light' => 'rgba-orange-light',
        'rgba-brown-light' => 'rgba-brown-light',
        'rgba-teal-light' => 'rgba-teal-light',
        'rgba-green-light' => 'rgba-green-light',
        'rgba-white-slight' => 'rgba-white-slight',
        'rgba-stylish-slight' => 'rgba-stylish-slight',
        'rgba-black-slight' => 'rgba-black-slight',
        'rgba-blue-grey-slight' => 'rgba-blue-grey-slight',
        'rgba-grey-slight' => 'rgba-grey-slight',
        'rgba-brown-slight' => 'rgba-brown-slight',
        'rgba-orange-slight' => 'rgba-orange-slight',
        'rgba-yellow-slight' => 'rgba-yellow-slight',
        'rgba-lime-slight' => 'rgba-lime-slight',
        'rgba-green-slight' => 'rgba-green-slight',
        'rgba-teal-slight' => 'rgba-teal-slight',
        'rgba-cyan-slight' => 'rgba-cyan-slight',
        'rgba-indigo-slight' => 'rgba-indigo-slight',
        'rgba-purple-slight' => 'rgba-purple-slight',
        'rgba-pink-slight' => 'rgba-pink-slight',
        'rgba-red-slight' => 'rgba-red-slight',
        'rgba-blue-slight' => ' rgba-blue-slight',
        'rgba-white-strong' => 'rgba-white-strong',
        'rgba-stylish-strong' => 'rgba-stylish-strong',
        'rgba-black-strong' => 'rgba-black-strong',
        'rgba-blue-grey-strong' => 'rgba-blue-grey-strong',
        'rgba-grey-strong' => 'rgba-grey-strong',
        'rgba-brown-strong' => 'rgba-brown-strong',
        'rgba-orange-strong' => 'rgba-orange-strong',
        'rgba-yellow-strong' => 'rgba-yellow-strong',
        'rgba-lime-strong' => 'rgba-lime-strong',
        'rgba-green-strong' => 'rgba-green-strong',
        'rgba-teal-strong' => 'rgba-teal-strong',
        'rgba-cyan-strong' => 'rgba-cyan-strong',
        'rgba-indigo-strong' => 'rgba-indigo-strong',
        'rgba-purple-strong' => 'rgba-purple-strong',
        'rgba-pink-strong' => 'rgba-pink-strong',
        'rgba-red-strong' => 'rgba-red-strong',
        'rgba-blue-strong' => 'rgba-blue-strong',
        'rgba-white-light' => 'rgba-white-light',
        'rgba-stylish-light' => 'rgba-stylish-light',
        'rgba-black-light' => 'rgba-black-light',
        'rgba-blue-grey-light' => 'rgba-blue-grey-light',
        'rgba-grey-light' => 'rgba-grey-light',
        'rgba-lime-light' => 'rgba-lime-light',
        'rgba-yellow-light' => 'rgba-yellow-light',
        'rgba-onrange-light' => 'rgba-brown-light',
        'elegant-color-dark' => 'stylish-color-dark',
        'red lighten-5' => 'red lighten-5',
        'red lighten-4' => 'red lighten-4',
        'red lighten-3' => 'red lighten-3',
        'red lighten-2' => 'red lighten-2',
        'red lighten-1' => 'red lighten-1',
        'red darken-4' => 'red darken-4',
        'red darken-3' => 'red darken-3',
        'red darken-2' => 'red darken-2',
        'red darken-1' => 'red darken-1',
        'red accent-1' => 'red accent-1',
        'red accent-2' => 'red accent-2',
        'red accent-3' => 'red accent-3',
        'red accent-4' => 'red accent-4',
        'pink lighten-5' => 'pink lighten-5',
        'pink lighten-4' => 'pink lighten-4',
        'pink lighten-3' => 'pink lighten-3',
        'pink lighten-2' => 'pink lighten-2',
        'pink lighten-1' => 'pink lighten-1',
        'pink darken-4' => 'pink darken-4',
        'pink darken-3' => 'pink darken-3',
        'pink darken-2' => 'pink darken-2',
        'pink darken-1' => 'pink darken-1',
        'pink accent-1' => 'pink accent-1',
        'pink accent-2' => 'pink accent-2',
        'pink accent-3' => 'pink accent-3',
        'pink accent-4' => 'pink accent-4',
        'purple lighten-5' => 'purple lighten-5',
        'purple lighten-4' => 'purple lighten-4',
        'purple lighten-3' => 'purple lighten-3',
        'purple lighten-2' => 'purple lighten-2',
        'purple lighten-1' => 'purple lighten-1',
        'purple' => 'purple',
        'purple darken-4' => 'purple darken-4',
        'purple darken-3' => 'purple darken-3',
        'purple darken-2' => 'purple darken-2',
        'purple darken-1' => 'purple darken-1',
        'purple accent-1' => 'purple accent-1',
        'purple accent-2' => 'purple accent-2',
        'purple accent-3' => 'purple accent-3',
        'purple accent-4' => 'purple accent-4',
        'deep-purple lighten-5' => 'deep-purple lighten-5',
        'deep-purple lighten-4' => 'deep-purple lighten-4',
        'deep-purple lighten-3' => 'deep-purple lighten-3',
        'deep-purple lighten-2' => 'deep-purple lighten-2',
        'deep-purple lighten-1' => 'deep-purple lighten-1',
        'deep-purple darken-4' => 'deep-purple darken-4',
        'deep-purple darken-3' => 'deep-purple darken-3',
        'deep-purple darken-2' => 'deep-purple darken-2',
        'deep-purple darken-1' => 'deep-purple darken-1',
        'deep-purple accent-1' => 'deep-purple accent-1',
        'deep-purple accent-2' => 'deep-purple accent-2',
        'deep-purple accent-3' => 'deep-purple accent-3',
        'deep-purple accent-4' => 'deep-purple accent-4',
        'indigo lighten-5' => 'indigo lighten-5',
        'indigo lighten-4' => 'indigo lighten-4',
        'indigo lighten-3' => 'indigo lighten-3',
        'indigo lighten-2' => 'indigo lighten-2',
        'indigo lighten-1' => 'indigo lighten-1',
        'indigo darken-4' => 'indigo darken-4',
        'indigo darken-3' => 'indigo darken-3',
        'indigo darken-2' => 'indigo darken-2',
        'indigo darken-1' => 'indigo darken-1',
        'indigo accent-1' => 'indigo accent-1',
        'indigo accent-2' => 'indigo accent-2',
        'indigo accent-3' => 'indigo accent-3',
        'indigo accent-4' => 'indigo accent-4',
        'blue lighten-5' => 'blue lighten-5',
        'blue lighten-4' => 'blue lighten-4',
        'blue lighten-3' => 'blue lighten-3',
        'blue lighten-2' => 'blue lighten-2',
        'blue lighten-1' => 'blue lighten-1',
        'blue darken-4' => 'blue darken-4',
        'blue darken-3' => 'blue darken-3',
        'blue darken-2' => 'blue darken-2',
        'blue darken-1' => 'blue darken-1',
        'blue accent-1' => 'blue accent-1',
        'blue accent-2' => 'blue accent-2',
        'blue accent-3' => 'blue accent-3',
        'blue accent-4' => 'blue accent-4',
        'light-blue lighten-5' => 'light-blue lighten-5',
        'light-blue lighten-4' => 'light-blue lighten-4',
        'light-blue lighten-3' => 'light-blue lighten-3',
        'light-blue lighten-2' => 'light-blue lighten-2',
        'light-blue lighten-1' => 'light-blue lighten-1',
        'light-blue darken-4' => 'light-blue darken-4',
        'light-blue darken-3' => 'light-blue darken-3',
        'light-blue darken-2' => 'light-blue darken-2',
        'light-blue darken-1' => 'light-blue darken-1',
        'light-blue accent-1' => 'light-blue accent-1',
        'light-blue accent-2' => 'light-blue accent-2',
        'light-blue accent-3' => 'light-blue accent-3',
        'light-blue accent-4' => 'light-blue accent-4',
        'cyan lighten-5' => 'cyan lighten-5',
        'cyan lighten-4' => 'cyan lighten-4',
        'cyan lighten-3' => 'cyan lighten-3',
        'cyan lighten-2' => 'cyan lighten-2',
        'cyan lighten-1' => 'cyan lighten-1',
        'cyan darken-4' => 'cyan darken-4',
        'cyan darken-3' => 'cyan darken-3',
        'cyan darken-2' => 'cyan darken-2',
        'cyan darken-1' => 'cyan darken-1',
        'cyan accent-1' => 'cyan accent-1',
        'cyan accent-2' => 'cyan accent-2',
        'cyan accent-3' => 'cyan accent-3',
        'cyan accent-4' => 'cyan accent-4',
        'teal lighten-5' => 'teal lighten-5',
        'teal lighten-4' => 'teal lighten-4',
        'teal lighten-3' => 'teal lighten-3',
        'teal lighten-2' => 'teal lighten-2',
        'teal lighten-1' => 'teal lighten-1',
        'teal darken-4' => 'teal darken-4',
        'teal darken-3' => 'teal darken-3',
        'teal darken-2' => 'teal darken-2',
        'teal darken-1' => 'teal darken-1',
        'teal accent-1' => 'teal accent-1',
        'teal accent-2' => 'teal accent-2',
        'teal accent-3' => 'teal accent-3',
        'teal accent-4' => 'teal accent-4',
        'green lighten-5' => 'green lighten-5',
        'green lighten-4' => 'green lighten-4',
        'green lighten-3' => 'green lighten-3',
        'green lighten-2' => 'green lighten-2',
        'green lighten-1' => 'green lighten-1',
        'green darken-4' => 'green darken-4',
        'green darken-3' => 'green darken-3',
        'green darken-2' => 'green darken-2',
        'green darken-1' => 'green darken-1',
        'green accent-1' => 'green accent-1',
        'green accent-2' => 'green accent-2',
        'green accent-3' => 'green accent-3',
        'green accent-4' => 'green accent-4',
        'light-green lighten-5' => 'light-green lighten-5',
        'light-green lighten-4' => 'light-green lighten-4',
        'light-green lighten-3' => 'light-green lighten-3',
        'light-green lighten-2' => 'light-green lighten-2',
        'light-green lighten-1' => 'light-green lighten-1',
        'light-green darken-4' => 'light-green darken-4',
        'light-green darken-3' => 'light-green darken-3',
        'light-green darken-2' => 'light-green darken-2',
        'light-green darken-1' => 'light-green darken-1',
        'light-green accent-1' => 'light-green accent-1',
        'light-green accent-2' => 'light-green accent-2',
        'light-green accent-3' => 'light-green accent-3',
        'light-green accent-4' => 'light-green accent-4',
        'lime lighten-5' => 'lime lighten-5',
        'lime lighten-4' => 'lime lighten-4',
        'lime lighten-3' => 'lime lighten-3',
        'lime lighten-2' => 'lime lighten-2',
        'lime lighten-1' => 'lime lighten-1',
        'lime darken-4' => 'lime darken-4',
        'lime darken-3' => 'lime darken-3',
        'lime darken-2' => 'lime darken-2',
        'lime darken-1' => 'lime darken-1',
        'lime accent-1' => 'lime accent-1',
        'lime accent-2' => 'lime accent-2',
        'lime accent-3' => 'lime accent-3',
        'lime accent-4' => 'lime accent-4',
        'yellow lighten-5' => 'yellow lighten-5',
        'yellow lighten-4' => 'yellow lighten-4',
        'yellow lighten-3' => 'yellow lighten-3',
        'yellow lighten-2' => 'yellow lighten-2',
        'yellow lighten-1' => 'yellow lighten-1',
        'yellow darken-4' => 'yellow darken-4',
        'yellow darken-3' => 'yellow darken-3',
        'yellow darken-2' => 'yellow darken-2',
        'yellow darken-1' => 'yellow darken-1',
        'yellow accent-1' => 'yellow accent-1',
        'yellow accent-2' => 'yellow accent-2',
        'yellow accent-3' => 'yellow accent-3',
        'yellow accent-4' => 'yellow accent-4',
        'amber lighten-5' => 'amber lighten-5',
        'amber lighten-4' => 'amber lighten-4',
        'amber lighten-3' => 'amber lighten-3',
        'amber lighten-2' => 'amber lighten-2',
        'amber lighten-1' => 'amber lighten-1',
        'amber darken-4' => 'amber darken-4',
        'amber darken-3' => 'amber darken-3',
        'amber darken-2' => 'amber darken-2',
        'amber darken-1' => 'amber darken-1',
        'amber accent-1' => 'amber accent-1',
        'amber accent-2' => 'amber accent-2',
        'amber accent-3' => 'amber accent-3',
        'amber accent-4' => 'amber accent-4',
        'orange lighten-5' => 'orange lighten-5',
        'orange lighten-4' => 'orange lighten-4',
        'orange lighten-3' => 'orange lighten-3',
        'orange lighten-2' => 'orange lighten-2',
        'orange lighten-1' => 'orange lighten-1',
        'orange darken-4' => 'orange darken-4',
        'orange darken-3' => 'orange darken-3',
        'orange darken-2' => 'orange darken-2',
        'orange darken-1' => 'orange darken-1',
        'orange accent-1' => 'orange accent-1',
        'orange accent-2' => 'orange accent-2',
        'orange accent-3' => 'orange accent-3',
        'orange accent-4' => 'orange accent-4',
        'deep-orange lighten-5' => 'deep-orange lighten-5',
        'deep-orange lighten-4' => 'deep-orange lighten-4',
        'deep-orange lighten-3' => 'deep-orange lighten-3',
        'deep-orange lighten-2' => 'deep-orange lighten-2',
        'deep-orange lighten-1' => 'deep-orange lighten-1',
        'deep-orange darken-4' => 'deep-orange darken-4',
        'deep-orange darken-3' => 'deep-orange darken-3',
        'deep-orange darken-2' => 'deep-orange darken-2',
        'deep-orange darken-1' => 'deep-orange darken-1',
        'deep-orange accent-1' => 'deep-orange accent-1',
        'deep-orange accent-2' => 'deep-orange accent-2',
        'deep-orange accent-3' => 'deep-orange accent-3',
        'deep-orange accent-4' => 'deep-orange accent-4',
        'brown lighten-5' => 'brown lighten-5',
        'brown lighten-4' => 'brown lighten-4',
        'brown lighten-3' => 'brown lighten-3',
        'brown lighten-2' => 'brown lighten-2',
        'brown lighten-1' => 'brown lighten-1',
        'brown darken-4' => 'brown darken-4',
        'brown darken-3' => 'brown darken-3',
        'brown darken-2' => 'brown darken-2',
        'brown darken-1' => 'brown darken-1',
        'grey lighten-5' => 'grey lighten-5',
        'grey lighten-4' => 'grey lighten-4',
        'grey lighten-3' => 'grey lighten-3',
        'grey lighten-2' => 'grey lighten-2',
        'grey lighten-1' => 'grey lighten-1',
        'grey darken-4' => 'grey darken-4',
        'grey darken-3' => 'grey darken-3',
        'grey darken-2' => 'grey darken-2',
        'grey darken-1' => 'grey darken-1',
        'blue-grey lighten-5' => 'blue-grey lighten-5',
        'blue-grey lighten-4' => 'blue-grey lighten-4',
        'blue-grey lighten-3' => 'blue-grey lighten-3',
        'blue-grey lighten-2' => 'blue-grey lighten-2',
        'blue-grey lighten-1' => 'blue-grey lighten-1',
        'blue-grey darken-4' => 'blue-grey darken-4',
        'blue-grey darken-3' => 'blue-grey darken-3',
        'blue-grey darken-2' => 'blue-grey darken-2',
        'blue-grey darken-1' => 'blue-grey darken-1',
        'mdb-color lighten-5' => 'mdb-color lighten-5',
        'mdb-color lighten-4' => 'mdb-color lighten-4',
        'mdb-color lighten-3' => 'mdb-color lighten-3',
        'mdb-color lighten-2' => 'mdb-color lighten-2',
        'mdb-color lighten-1' => 'mdb-color lighten-1',
        'mdb-color darken-4' => 'mdb-color darken-4',
        'mdb-color darken-3' => 'mdb-color darken-3',
        'mdb-color darken-2' => 'mdb-color darken-2',
        'mdb-color darken-1' => 'mdb-color darken-1',
        'transparent' => 'transparent',
        'wheat' => 'wheat'
    ];

    public const gradient = [

        //basic
        'purple-gradient' => 'purple-gradient',
        'blue-gradient' => 'blue-gradient',
        'aqua-gradient' => 'aqua-gradient',
        'peach-gradient' => 'peach-gradient',

        //additional
        'warm-flame-gradient' => 'warm-flame-gradient',
        'night-fade-gradient' => 'night-fade-gradient',
        'spring-warmth-gradient' => 'spring-warmth-gradient',
        'near-moon-gradient' => 'near-moon-gradient',
        'rare-wind-gradient' => 'rare-wind-gradient',
        'morpheus-den-gradient' => 'morpheus-den-gradient',
        'cloudy-knoxville-gradient' => 'cloudy-knoxville-gradient',
        'ripe-malinka-gradient' => 'ripe-malinka-gradient',
        'deep-blue-gradient' => 'deep-blue-gradient',
        'mean-fruit-gradient' => 'mean-fruit-gradient',
        'amy-crisp-gradient' => 'amy-crisp-gradient',
        'heavy-rain-gradient' => 'heavy-rain-gradient',
        'tempting-azure-gradient' => 'tempting-azure-gradient',
        'dusty-grass-gradient' => 'dusty-grass-gradient',
        'frozen-dreams-gradient' => 'frozen-dreams-gradient',
        'winter-neva-gradient' => 'winter-neva-gradient',
        'lady-lips-gradient' => 'lady-lips-gradient',
        'sunny-morning-gradient' => 'sunny-morning-gradient',
        'rainy-ashville-gradient' => 'rainy-ashville-gradient',
        'young-passion-gradient' => 'young-passion-gradient',
        'juicy-peach-gradient' => 'juicy-peach-gradient',
    ];


    public const btnStyle = [
        'none' => '',
        'btn-primary' => 'btn-primary',
        'btn-default' => 'btn-default',
        'btn-secondary' => 'btn-secondary',
        'btn-success' => 'btn-success',
        'btn-danger' => 'btn-danger',
        'btn-warning' => 'btn-warning',

        'btn-info' => 'btn-info',
        'btn-light' => 'btn-light',
        'btn-dark' => 'btn-dark',
        'btn-link' => 'btn-link',
        'btn-blue-grey' => 'btn-blue-grey',

        'btn-outline-primary' => 'btn-outline-primary waves-effect',
        'btn-outline-default' => 'btn-outline-default waves-effect',
        'btn-outline-secondary' => 'btn-outline-secondary waves-effect',
        'btn-outline-success' => 'btn-outline-success waves-effect',
        'btn-outline-danger' => 'btn-outline-danger waves-effect',
        'btn-outline-danger rounded-0' => 'btn-outline-danger waves-effect rounded-0',
        'btn-outline-warning' => 'btn-outline-warning waves-effect',
        'btn-outline-info' => 'btn-outline-info waves-effect',
        'btn-outline-light' => 'btn-outline-light waves-effect',
        'btn-outline-dark' => 'btn-outline-dark waves-effect',
        'btn-outline-link' => 'btn-outline-link waves-effect',
        'btn-transparent' => 'btn-transparent',
    ];


    public const mask = [
        //mask patterns
        'pattern-1' => 'pattern-1',
        'pattern-2' => 'pattern-2',
        'pattern-3' => 'pattern-3',
        'pattern-4' => 'pattern-4',
        'pattern-5' => 'pattern-5',
        'pattern-6' => 'pattern-6',
        'pattern-7' => 'pattern-7',
        'pattern-8' => 'pattern-8',
        'pattern-9' => 'pattern-9',
    ];

    public const skin = [
        'white-skin' => 'white-skin',
        'black-skin' => 'black-skin',
        'cyan-skin' => 'cyan-skin',
        'mdb-skin' => 'mdb-skin',
        'deep-purple-skin' => 'deep-purple-skin',
        'navy-blue-skin' => 'navy-blue-skin',
        'pink-skin' => 'pink-skin',
        'indigo-skin' => 'indigo-skin',
        'light-blue-skin' => 'light-blue-skin',
        'grey-skin' => 'grey-skin',
    ];

}
